### ISSUE TITLE
PATO URIs are not correct

### ISSUE THREAD

**Issue by cmungall** [aellenhicks/htn_owl#6]
This uses the very old (>10yo?) OBO URIs for PATO:

http://purl.org/obo/owl/PATO#PATO_0000161

**Comment by aellenhicks** [comment]
Fixed thank you. These were imported by VSO. I'm not sure if it is under development, but contacted Albert Goldfain per VSO's [page](https://bioportal.bioontology.org/ontologies/VSO) on Bioportal.
